version: "3.8"
services:
  postgres:
    image: registry.gitlab.com/dalibo/postgresql_anonymizer:stable
    container_name: pg-anonymizer
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "6543:5432"
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: